// Generate jason-26 through jason-150 (125 hard/linguistic puzzles)
// Each puzzle: 4 categories with 4 words each and a color

const ALL_CATEGORIES = [
  // --- PREFIXES ---
  {name:"PREFIJO 'RE-'", words:["RENACER","REPASAR","RECARGAR","RELLENAR"]},
  {name:"PREFIJO 'IN-'", words:["INCREIBLE","INVISIBLE","INEXACTO","INUTIL"]},
  {name:"PREFIJO 'SUB-'", words:["SUBTERRANEO","SUBACUATICO","SUBTITULO","SUBMARINO"]},
  {name:"PREFIJO 'PRE-'", words:["PREHISTORIA","PREESCOLAR","PREVIO","PREPAGO"]},
  {name:"PREFIJO 'DES-'", words:["DESCONOCIDO","DESAPARECER","DESCUBRIR","DESARMAR"]},
  {name:"PREFIJO 'ANTI-'", words:["ANTIAEREO","ANTIBIOTICO","ANTISOCIAL","ANTINATURAL"]},
  {name:"PREFIJO 'MULTI-'", words:["MULTICOLOR","MULTINACIONAL","MULTIMEDIA","MULTIUSO"]},
  {name:"PREFIJO 'BIO-'", words:["BIOLOGIA","BIODIVERSIDAD","BIOMASA","BIOGRAFIA"]},
  {name:"PREFIJO 'AUTO-'", words:["AUTOMOVIL","AUTOPISTA","AUTOMATICO","AUTONOMO"]},
  {name:"PREFIJO 'SUPER-'", words:["SUPERMERCADO","SUPERHOMBRE","SUPERFICIE","SUPERPOTENCIA"]},
  {name:"PREFIJO 'TELE-'", words:["TELEVISION","TELEFONO","TELESCOPIO","TELEGRAMA"]},
  {name:"PREFIJO 'MICRO-'", words:["MICROONDAS","MICROSCOPIO","MICROCHIP","MICROFONO"]},
  {name:"PREFIJO 'HIPER-'", words:["HIPERMERCADO","HIPERTENSION","HIPERSENSIBLE","HIPERACTIVO"]},

  // --- SUFFIXES ---
  {name:"SUFIJO '-CION'", words:["ACCION","CANCION","VISION","MISION"]},
  {name:"SUFIJO '-MENTE'", words:["RAPIDAMENTE","FACILMENTE","LENTAMENTE","SUAVEMENTE"]},
  {name:"SUFIJO '-DAD'", words:["LIBERTAD","BONDAD","MALDAD","HERMANDAD"]},
  {name:"SUFIJO '-ERO'", words:["CARTERO","PANADERO","JARDINERO","CARPINTERO"]},
  {name:"SUFIJO '-ISTA'", words:["ARTISTA","PIANISTA","PERIODISTA","CIENTIFICO"]},
  {name:"SUFIJO '-OSO'", words:["PELIGROSO","MARAVILLOSO","HERMOSO","CUIDADOSO"]},
  {name:"TERMINAN EN '-AJE'", words:["VIAJE","PAISAJE","LENGUAJE","EQUIPAJE"]},
  {name:"TERMINAN EN '-UCHO'", words:["POBLUCHO","VIVIENDUCHO","CASUCHO","CUARTUCHO"]},
  {name:"TERMINAN EN '-AZO'", words:["PEDRAZO","PORTAZO","PUÑETAZO","BALONAZO"]},

  // --- STARTING WITH ---
  {name:"EMPIEZAN CON 'H'", words:["HUEVO","HUESO","HIELO","HUERTO"]},
  {name:"EMPIEZAN CON 'CH'", words:["CHOCOLATE","CHILE","CHANCLA","CHIMENEA"]},
  {name:"EMPIEZAN CON 'LL'", words:["LLAVE","LLUVIA","LLANTA","LLAMA"]},
  {name:"EMPIEZAN CON 'Y'", words:["YEMA","YATE","YELMO","YERBA"]},
  {name:"EMPIEZAN CON 'Z'", words:["ZAPATO","ZORRO","ZANAHORIA","ZARZA"]},
  {name:"EMPIEZAN CON 'P' Y ACABAN EN 'O'", words:["PERRO","PLATO","PUERTO","PINO"]},

  // --- LETTERS / PHONETICS ---
  {name:"PALABRAS CON 'B'", words:["BOLSO","BARCO","BICICLETA","BOTA"]},
  {name:"PALABRAS CON 'V'", words:["VACA","VASO","VENTANA","VERDE"]},
  {name:"PALABRAS CON 'Ñ'", words:["ESPANA","ANO","MUNECA","PINA"]},
  {name:"PALABRAS CON 'X'", words:["EXAMEN","TEXTO","FLEXIBLE","EXCELENTE"]},
  {name:"PALABRAS CON 'Q'", words:["QUESO","QUEMAR","QUITAR","QUERER"]},
  {name:"PALABRAS CON DOBLE 'R'", words:["CARRETERA","ARROZ","BARRIL","CORREDOR"]},
  {name:"PALABRAS CON 'LL'", words:["LLAVE","LLUVIA","CALLE","POLLO"]},
  {name:"PALABRAS CON 'TR'", words:["TREN","TREMENTINA","TRENZA","TRIANGULO"]},
  {name:"PALABRAS CON 'GR'", words:["GRANDE","GRITO","GRIS","GRUESO"]},
  {name:"PALABRAS CON 'PL'", words:["PLATO","PLUMA","PLANTA","PLAZA"]},
  {name:"PALABRAS CON 'FR'", words:["FRUTA","FRIO","FRENO","FRENTE"]},
  {name:"PALABRAS CON 'BR'", words:["BRAZO","BROCHA","BRUJA","BRUJULA"]},

  // --- ACCENTUATION ---
  {name:"PALABRAS AGUDAS", words:["CAFE","SOFA","AVION","BALON"]},
  {name:"PALABRAS GRAVES", words:["ARBOL","CARPETA","LIBRO","MESA"]},
  {name:"PALABRAS ESDRUJULAS", words:["MEDICO","PAGINA","TECNICO","MUSICA"]},
  {name:"PALABRAS SOBRESDRUJULAS", words:["DIGAMELO","COMPRAMELO","ENSENAMELO","BUSCAMELO"]},
  {name:"MONOSILABAS", words:["SOL","MAR","LUZ","PAN"]},
  {name:"BISILABAS", words:["CASA","MESA","GATO","PERRO"]},
  {name:"TRISILABAS", words:["VENTANA","CAMISA","ZAPATO","ABRIGO"]},
  {name:"SIN ACENTO", words:["SOL","MAR","LUZ","PAN"]},
  {name:"CON ACENTO FINAL", words:["CAFE","SOFA","AVION","BALON"]},

  // --- SYNONYMS ---
  {name:"SINONIMO DE 'INTELIGENTE'", words:["LISTO","SABIO","DOCTO","ERUDITO"]},
  {name:"SINONIMO DE 'FEO'", words:["HORRIBLE","MONSTRUOSO","DEFORME","REPUGNANTE"]},
  {name:"SINONIMO DE 'FELIZ'", words:["ALEGRE","CONTENTO","JUBILOSO","RADIANTE"]},
  {name:"SINONIMO DE 'TRISTE'", words:["APENADO","DECAIDO","MELANCOLICO","DEPRIMIDO"]},
  {name:"SINONIMO DE 'VALIENTE'", words:["AUDAS","OSADO","BRAVO","HECHO"]},
  {name:"SINONIMO DE 'ANTIGUO'", words:["VIEJO","ARCAICO","ANCESTRAL","PRIMITIVO"]},
  {name:"SINONIMO DE 'RAPIDO'", words:["VELOZ","AGIL","PRESTO","VERTIGINOSO"]},
  {name:"SINONIMO DE 'GRANDE'", words:["ENORME","GIGANTESCO","COLOSAL","MONSTRUOSO"]},
  {name:"SINONIMO DE 'HERMOSO'", words:["BELLO","PRECIOSO","BONITO","LIMPIO"]},
  {name:"SINONIMO DE 'DIFICIL'", words:["COMPLICADO","LABORIOSO","ARDIO","TORPE"]},
  {name:"SINONIMO DE 'SENCILLO'", words:["FACIL","SIMPLE","BASICO","ELEMENTAL"]},

  // --- ANTONYMS ---
  {name:"ANTONIMO DE 'BUENO'", words:["MALO","PERVERSO","VILEZA","MALDAD"]},
  {name:"ANTONIMO DE 'FACIL'", words:["DIFICIL","COMPLEJO","ENREDADO","LABORIOSO"]},
  {name:"ANTONIMO DE 'LLENO'", words:["VACIO","HUECO","DESOCUPADO","LIBRE"]},
  {name:"ANTONIMO DE 'ALEGRE'", words:["TRISTE","APAGADO","SOMBRIO","MUSTIO"]},
  {name:"ANTONIMO DE 'FUERTE'", words:["DEBIL","FRAGIL","FLOJO","LIVIANO"]},
  {name:"ANTONIMO DE 'NUEVO'", words:["VIEJO","USADO","GASTADO","ANTIGUO"]},
  {name:"ANTONIMO DE 'ALTO'", words:["BAJO","CHICO","PEQUENO","REDUCIDO"]},

  // --- POS / Grammar ---
  {name:"VERBOS EN INFINITIVO", words:["CORRER","SALTAR","COMER","VIVIR"]},
  {name:"VERBOS IRREGULARES", words:["TENER","PONER","SALIR","VENIR"]},
  {name:"VERBOS REGULARES 'AR'", words:["HABLAR","LLEGAR","BUSCAR","COMPRAR"]},
  {name:"VERBOS REGULARES 'ER'", words:["BEBER","CORRER","LEER","VENDER"]},
  {name:"VERBOS REGULARES 'IR'", words:["VIVIR","ESCRIBIR","RECIBIR","ABRIR"]},
  {name:"VERBOS DE MOVIMIENTO", words:["IR","VENIR","LLEGAR","SALIR"]},
  {name:"VERBOS DE COCINA", words:["HERVIR","FREIR","HORNEAR","ASAR"]},
  {name:"VERBOS DE PERCEPCION", words:["VER","OIR","OLER","SENTIR"]},
  {name:"VERBOS REFLEXIVOS", words:["LEVANTARSE","DUCHARSE","VESTIRSE","ACOSTARSE"]},
  {name:"SUSTANTIVOS ABSTRACTOS", words:["ESPERANZA","LIBERTAD","JUSTICIA","IGUALDAD"]},
  {name:"SUSTANTIVOS COLECTIVOS", words:["MANADA","REBANO","EJERCITO","FLOTA"]},
  {name:"ADJETIVOS CALIFICATIVOS", words:["AMABLE","GENEROSO","CARINOSO","PACIENTE"]},
  {name:"ADJETIVOS NUMERALES", words:["PRIMERO","SEGUNDO","TERCERO","ULTIMO"]},
  {name:"ADJETIVOS DE TAMANO", words:["MINUSCULO","ENANO","GIGANTE","PEQUENO"]},
  {name:"PALABRAS COMPUESTAS", words:["PARAGUAS","CORREVEIDILE","SACACORCHOS","PORTAFOLIO"]},
  {name:"AUMENTATIVOS", words:["PERRAZO","GATOTE","CASOTA","BIGOTE"]},
  {name:"DIMINUTIVOS", words:["PERRITO","GATITO","CASITA","ARBOLITO"]},
  {name:"PRONOMBRES PERSONALES", words:["YO","TU","EL","ELLA"]},
  {name:"PREPOSICIONES", words:["A","ANTE","BAJO","CON"]},
  {name:"CONJUNCIONES", words:["Y","O","PERO","PORQUE"]},

  // --- WORDPLAY ---
  {name:"PALABRAS HOMOFONAS", words:["VACA","BACA","HOLA","OLA"]},
  {name:"PALABRAS HOMOGRAFAS", words:["RIO","VINO","COMO","CALLE"]},
  {name:"PALABRAS POLISEMICAS", words:["BANCO","CARTA","SILLA","VELA"]},
  {name:"PALABRAS PALINDROMAS", words:["SALAS","RECONOCER","SOMOS","ANILINA"]},
  {name:"PALABRAS ONOMATOPEYICAS", words:["GUAU","MIAU","MU","BEE"]},
  {name:"PALABRAS TABU", words:["PALABRO","INSULTO","MALEDUCACION","GROSERIA"]},
  {name:"PALABRAS DE ORIGEN ARABE", words:["ALMOHADA","ALGODON","ALMACEN","AZUCAR"]},
  {name:"PALABRAS DE ORIGEN NAHUATL", words:["CHOCOLATE","TOMATE","AGUACATE","CHILE"]},
  {name:"PALABRAS DE ORIGEN INGLES", words:["JAZZ","CLUB","WHISKY","FUTBOL"]},
  {name:"PALABRAS DE DOBLE SENTIDO", words:["PICO","GATO","LIMA","SERIE"]},
  {name:"PALABRAS CON METATESIS", words:["MURCIELAGO","CROQUETA","ALMOHADA","AEROPUERTO"]},

  // --- SCIENCE ---
  {name:"ELEMENTOS QUIMICOS", words:["ORO","PLATA","COBRE","HIERRO"]},
  {name:"GASES NOBLES", words:["HELIO","NEON","ARGON","KRIPTON"]},
  {name:"METALES PRECIOSOS", words:["DIAMANTE","ESMERALDA","RUBI","ZAFIRO"]},
  {name:"PLANETAS ENANOS", words:["PLUTON","ERIS","MAKEMAKE","HAUMEA"]},
  {name:"TIPOS DE ENERGIA", words:["SOLAR","EOLICA","HIDRAULICA","NUCLEAR"]},
  {name:"FUERZAS FISICAS", words:["GRAVEDAD","MAGNETISMO","ELECTRICA","FRICCION"]},
  {name:"RAMAS DE BIOLOGIA", words:["BOTANICA","ZOOLOGIA","GENETICA","ECOLOGIA"]},
  {name:"RAMAS DE FISICA", words:["MECANICA","TERMODINAMICA","OPTICA","ACUSTICA"]},
  {name:"UNIDADES DE MEDIDA", words:["METRO","LITRO","KILO","SEGUNDO"]},
  {name:"INSTRUMENTOS CIENTIFICOS", words:["ESTETOSCOPIO","TERMOMETRO","JERINGA","TENSOMETRO"]},
  {name:"HUESOS DEL CUERPO", words:["FEMUR","TIBIA","HUMERO","COSTILLA"]},
  {name:"MUSCULOS PRINCIPALES", words:["BICEPS","TRICEPS","CUADRICEPS","ABDOMINAL"]},
  {name:"ORGANOS VITALES", words:["CORAZON","PULMON","HIGADO","RINON"]},
  {name:"SENTIDOS HUMANOS", words:["VISTA","OIDO","OLFATO","GUSTO"]},
  {name:"PARTES DEL OJO", words:["IRIS","PUPILA","RETINA","CORNEA"]},
  {name:"GLANDULAS ENDOCRINAS", words:["TIROIDES","PANCREAS","HIPOFISIS","SUPRARRENAL"]},
  {name:"SISTEMAS DEL CUERPO", words:["RESPIRATORIO","DIGESTIVO","CIRCULATORIO","NERVIOSO"]},
  {name:"CAPAS ATMOSFERICAS", words:["TROPOSFERA","ESTRATOSFERA","MESOSFERA","TERMOSFERA"]},
  {name:"PLACAS TECTONICAS", words:["PACIFICA","AFRICANA","EUROASIATICA","NORTEAMERICANA"]},
  {name:"ESTADOS DE AGREGACION", words:["SOLIDO","LIQUIDO","GASEOSO","PLASMA"]},
  {name:"TIPOS DE NUBES", words:["CUMULUS","STRATUS","CIRRUS","NIMBUS"]},

  // --- GEOGRAPHY ---
  {name:"CAPITALES EUROPEAS", words:["PARIS","ROMA","BERLIN","LONDRES"]},
  {name:"CAPITALES AMERICANAS", words:["LIMA","BRASILIA","OTTAWA","BUENOS AIRES"]},
  {name:"CAPITALES ASIATICAS", words:["TOKIO","SEUL","PEKIN","BANGKOK"]},
  {name:"DESIERTOS FAMOSOS", words:["SAHARA","GOBI","ATACAMA","ARABIA"]},
  {name:"VOLCANES ACTIVOS", words:["VESUBIO","ETNA","FUJI","KRAKATOA"]},
  {name:"RIOS DE AMERICA", words:["AMAZONAS","MISISIPI","BRAVO","PARANA"]},
  {name:"RIOS DE EUROPA", words:["DANUBIO","RIN","SENA","TAJO"]},
  {name:"LAGOS FAMOSOS", words:["TITICACA","VICTORIA","SUPERIOR","GINEBRA"]},
  {name:"CORDILLERAS", words:["ANDES","HIMALAYA","ALPES","ROCHOSAS"]},
  {name:"OCEANOS DEL MUNDO", words:["PACIFICO","ATLANTICO","INDICO","ARTICO"]},
  {name:"CONTINENTES", words:["AMERICA","EUROPA","ASIA","AFRICA"]},
  {name:"PAISES SIN MAR", words:["SUIZA","BOLIVIA","AUSTRIA","HUNGRIA"]},
  {name:"PAISES INSULARES", words:["JAPON","CUBA","MADAGASCAR","FILIPINAS"]},
  {name:"PAISES NORDICOS", words:["SUECIA","NORUEGA","DINAMARCA","FINLANDIA"]},
  {name:"PAISES DE AFRICA", words:["EGIPTO","KENIA","MARRUECOS","SUDAFRICA"]},
  {name:"CIUDADES ESPANOLAS", words:["BARCELONA","MADRID","VALENCIA","SEVILLA"]},
  {name:"CIUDADES MEXICANAS", words:["CANCUN","GUADALAJARA","MONTERREY","PUEBLA"]},
  {name:"PUEBLOS INDIGENAS", words:["MAYA","AZTECA","INCA","GUARANI"]},
  {name:"ISLAS FAMOSAS", words:["HAWAI","BALI","MADAGASCAR","CUBA"]},
  {name:"ESTRECHOS MARITIMOS", words:["GIBRALTAR","BOSFORO","DARDANELOS","MAGELLANES"]},

  // --- MUSIC ---
  {name:"INSTRUMENTOS VIENTO", words:["FLAUTA","CLARINETE","TROMPETA","SAXOFON"]},
  {name:"INSTRUMENTOS CUERDA", words:["GUITARRA","VIOLIN","CELLO","ARPA"]},
  {name:"INSTRUMENTOS PERCUSION", words:["BATERIA","TAMBOR","MARIMBA","XILOFONO"]},
  {name:"GENEROS MUSICALES", words:["JAZZ","ROCK","POP","REGGAETON"]},
  {name:"RITMOS LATINOS", words:["SALSA","MERENGUE","CUMBIA","BACHATA"]},
  {name:"COMPOSITORES CLASICOS", words:["BEETHOVEN","MOZART","BACH","CHOPIN"]},
  {name:"NOTAS MUSICALES", words:["DO","RE","MI","FA"]},
  {name:"ACORDES BASICOS", words:["MAYOR","MENOR","AUMENTADO","DISMINUIDO"]},
  {name:"CANCIONES POPULARES", words:["DESPACITO","GASOLINA","BAILANDO","LA MACARENA"]},
  {name:"TERMINOS MUSICALES", words:["ALEGRO","ANDANTE","PRESTO","LARGO"]},
  {name:"BANDAS FAMOSAS", words:["QUEEN","ROLLING STONES","LED ZEPPELIN","PINK FLOYD"]},

  // --- ART & CINEMA ---
  {name:"CORRIENTES PINTURA", words:["RENACIMIENTO","BARROCO","IMPRESIONISMO","CUBISMO"]},
  {name:"PINTORES FAMOSOS", words:["PICASSO","DALI","GOYA","VAN GOGH"]},
  {name:"ESTILOS ARQUITECTURA", words:["GOTICO","BARROCO","MODERNO","CLASICO"]},
  {name:"TECNICAS DE PINTURA", words:["OLEO","ACUARELA","PASTEL","CARBON"]},
  {name:"PELICULAS CLASICAS", words:["CASABLANCA","CIUDADANO KANE","LO QUE EL VIENTO","PSICOSIS"]},
  {name:"PELICULAS ANIMADAS", words:["TOY STORY","FROZEN","REY LEON","NEMO"]},
  {name:"DIRECTORES DE CINE", words:["SPIELBERG","NOLAN","TARANTINO","ALMODOVAR"]},
  {name:"GENEROS CINEMATOGRAFICOS", words:["ACCION","DRAMA","COMEDIA","TERROR"]},
  {name:"PERSONAJES DISNEY", words:["MICKEY","MINNIE","DONALD","GOOFY"]},
  {name:"PRINCESAS DISNEY", words:["BLANCA","CENICIENTA","AURORA","JASMIN"]},
  {name:"SUPERHEROES", words:["BATMAN","SUPERMAN","SPIDERMAN","IRONMAN"]},
  {name:"PERSONAJES MARVEL", words:["IRON MAN","CAPITAN","THOR","HULK"]},

  // --- MYTHOLOGY ---
  {name:"DIOSES GRIEGOS", words:["ZEUS","POSEIDON","HADES","ARES"]},
  {name:"DIOSAS GRIEGAS", words:["ATENEA","AFRODITA","ARTEMISA","HERA"]},
  {name:"DIOSES EGIPCIOS", words:["RA","ANUBIS","OSIRIS","HORUS"]},
  {name:"DIOSAS EGIPCIAS", words:["ISIS","BASTET","NUT","MAAT"]},
  {name:"DIOSES NORUEGOS", words:["ODIN","THOR","FREY","LOKI"]},
  {name:"DIOSES ROMANOS", words:["JUPITER","MARTE","MERCURIO","SATURNO"]},
  {name:"HEROES MITOLOGICOS", words:["HERCULES","AQUILES","TESEO","PERSEO"]},
  {name:"MONSTRUOS MITOLOGICOS", words:["MINOTAURO","MEDUSA","CICLOPE","HIDRA"]},
  {name:"SERES MITOLOGICOS", words:["CENTAURO","SIRENA","GRIFO","FENIX"]},
  {name:"TITANES", words:["CRONOS","ATLAS","PROMETEO","EPIMETEO"]},
  {name:"MUSAS GRIEGAS", words:["CALIOPE","TERPSICORE","URANIA","TALIA"]},

  // --- HISTORY ---
  {name:"CIVILIZACIONES ANTIGUAS", words:["EGIPTO","GRECIA","ROMA","MAYA"]},
  {name:"EMPERADORES ROMANOS", words:["JULIO CESAR","AUGUSTO","NERON","MARCO AURELIO"]},
  {name:"FARAONES EGIPCIOS", words:["RAMSES","TUTANKAMON","KEOPS","AKHENATON"]},
  {name:"EXPLORADORES FAMOSOS", words:["COLON","MAGELLANES","PIZARRO","CORTES"]},
  {name:"INVENTOS IMPORTANTES", words:["RUEDA","PAPEL","POLVORA","BRUJULA"]},
  {name:"MARAVILLAS ANTIGUAS", words:["PIRAMIDE","COLISEO","MAUSOLEO","FARO"]},
  {name:"MARAVILLAS MODERNAS", words:["CHICHEN ITZA","MACHU PICCHU","COLISEO","TAJ MAHAL"]},
  {name:"GUERRAS FAMOSAS", words:["MUNDIAL","CIVIL","VIETNAM","INDEPENDENCIA"]},
  {name:"REVOLUCIONES", words:["FRANCESA","MEXICANA","INDUSTRIAL","RUSA"]},
  {name:"IMPERIOS HISTORICOS", words:["ROMANO","PERSA","MONGOL","BIZANTINO"]},
  {name:"MONUMENTOS FAMOSOS", words:["TORRE EIFFEL","ESTATUA LIBERTAD","COLISEO","PIRAMIDES"]},
  {name:"LIDERES HISTORICOS", words:["GANDHI","MANDELA","LUTERO","CHURCHILL"]},

  // --- SPORTS ---
  {name:"DEPORTES OLIMPICOS", words:["ATLETISMO","NATACION","GIMNASIA","ESGRIMA"]},
  {name:"DEPORTES DE PELOTA", words:["FUTBOL","TENIS","BEISBOL","GOLF"]},
  {name:"DEPORTES ACUATICOS", words:["NATACION","SURF","REMO","BUCEO"]},
  {name:"DEPORTES INVIERNO", words:["ESQUI","PATINAJE","HOCKEY","TRINEO"]},
  {name:"DEPORTES EXTREMOS", words:["PARACAIDAS","BUNGEE","ALPINISMO","RAFTING"]},
  {name:"ARTES MARCIALES", words:["KARATE","JUDO","TAEKWONDO","KUNG FU"]},
  {name:"POSICIONES FUTBOL", words:["PORTERO","DEFENSA","MEDIO","DELANTERO"]},
  {name:"ACCIONES FUTBOL", words:["GOL","PENAL","FUERA LUGAR","CABEZA"]},
  {name:"MARCAS DEPORTIVAS", words:["NIKE","ADIDAS","PUMA","REEBOK"]},
  {name:"CLUBES FUTBOL", words:["REAL MADRID","BARCELONA","BOCA","RIVER"]},

  // --- TECHNOLOGY ---
  {name:"REDES SOCIALES", words:["FACEBOOK","TWITTER","INSTAGRAM","TIKTOK"]},
  {name:"LENGUAJES DE PROGRAMACION", words:["PYTHON","JAVASCRIPT","JAVA","C"]},
  {name:"SISTEMAS OPERATIVOS", words:["WINDOWS","MACOS","LINUX","ANDROID"]},
  {name:"NAVEGADORES WEB", words:["CHROME","FIREFOX","SAFARI","EDGE"]},
  {name:"PROTOCOLOS DE INTERNET", words:["HTTP","FTP","DNS","TCP"]},
  {name:"COMPONENTES PC", words:["RAM","SSD","GPU","CPU"]},
  {name:"PUERTOS DE PC", words:["USB","HDMI","ETHERNET","AUDIO"]},
  {name:"FORMATOS DE ARCHIVO", words:["PDF","JPEG","MP3","TXT"]},
  {name:"APPS DE MENSAJERIA", words:["WHATSAPP","TELEGRAM","SIGNAL","MESSENGER"]},
  {name:"PLATAFORMAS STREAMING", words:["NETFLIX","DISNEY","MAX","PRIME"]},
  {name:"TECNOLOGIA ANTIGUA", words:["FAX","DISQUETE","VHS","TELEFONO FIJO"]},
  {name:"DISPOSITIVOS MOVILES", words:["IPHONE","SAMSUNG","XIAOMI","HUAWEI"]},
  {name:"EDITORES DE CODIGO", words:["VS CODE","SUBLIME","INTELLIJ","VIM"]},
  {name:"EMPRESAS TECNOLOGIA", words:["GOOGLE","APPLE","MICROSOFT","META"]},
  {name:"REDES INALAMBRICAS", words:["WIFI","BLUETOOTH","NFC","5G"]},
  {name:"MISIONES ESPACIALES", words:["APOLO","ARTEMIS","VOYAGER","CURIOSITY"]},

  // --- FOOD ---
  {name:"TIPOS DE PAN", words:["BLANCO","INTEGRAL","CENTENO","MASA MADRE"]},
  {name:"TIPOS DE QUESO", words:["MOZZARELLA","CHEDDAR","SUIZO","PARMESANO"]},
  {name:"HIERBAS AROMATICAS", words:["ALBAHACA","ROMERO","OREGANO","PEREJIL"]},
  {name:"ESPECIAS", words:["CANELA","PIMIENTA","COMINO","AZAFRAN"]},
  {name:"CORTES DE CARNE", words:["LOMO","SOLOMILLO","CHULETA","PECHUGA"]},
  {name:"FRUTAS TROPICALES", words:["MANGO","PAPAYA","GUANABANA","RAMBUTAN"]},
  {name:"FRUTOS SECOS", words:["ALMENDRA","NUEZ","AVELLANA","MANI"]},
  {name:"POSTRES TIPICOS", words:["FLAN","HELADO","PASTEL","GELATINA"]},
  {name:"BEBIDAS CALIENTES", words:["CAFE","CHOCOLATE","MATE","INFUSION"]},
  {name:"BEBIDAS ALCOHOLICAS", words:["CERVEZA","VINO","TEQUILA","RON"]},
  {name:"COCINA MEXICANA", words:["TACO","TAMAL","POZOLE","MOLE"]},
  {name:"PLATOS TIPICOS", words:["PAELLA","TACOS","SUSHI","PASTA"]},
  {name:"COMIDA RAPIDA", words:["HAMBURGUESA","PIZZA","TACO","SANDWICH"]},
  {name:"INGREDIENTES BASICOS", words:["HARINA","AZUCAR","HUEVO","MANTEQUILLA"]},
  {name:"SABORES DE HELADO", words:["VAINILLA","CHOCOLATE","FRESA","MENTA"]},

  // --- NATURE ---
  {name:"ANIMALES MARINOS", words:["DELFIN","TIBURON","BALLENA","PULPO"]},
  {name:"AVES RAPACES", words:["AGUILA","HALCÓN","BUITRE","LECHUZA"]},
  {name:"ANIMALES NOCTURNOS", words:["BUHO","MURCIELAGO","LOBO","LUCIERNAGA"]},
  {name:"FELINOS SALVAJES", words:["LEON","TIGRE","PUMA","LEOPARDO"]},
  {name:"ANIMALES POLARES", words:["OSO POLAR","PINGUINO","FOCA","MOFETA"]},
  {name:"ANIMALES EN PELIGRO", words:["PANDA","TIGRE","ELEFANTE","GORILA"]},
  {name:"ANIMALES DE AFRICA", words:["LEON","ELEFANTE","JIRAFA","CEBRA"]},
  {name:"ANIMALES DE GRANJA", words:["VACA","CERDO","GALLINA","CABALLO"]},
  {name:"ANIMALES DOMESTICOS", words:["PERRO","GATO","HAMSTER","CONEJO"]},
  {name:"ANIMALES VENENOSOS", words:["SERPIENTE","ESCORPION","ARANA","MEDUSA"]},
  {name:"ANIMALES EXTINTOS", words:["DODO","MAMUT","TIGRE DIENTE","PEREZOSO GIGANTE"]},
  {name:"ANIMALES BEBES", words:["CACHORRO","GATITO","POLLITO","POTRILLO"]},
  {name:"PRIMATES", words:["MONO","GORILA","CHIMPANCE","ORANGUTAN"]},
  {name:"RAZAS DE PERROS", words:["LABRADOR","PASTOR","BULLDOG","CHIHUAHUA"]},
  {name:"TIPOS DE ARBOLES", words:["ROBLE","PINO","SAUCE","CEDRO"]},
  {name:"FLORES COMUNES", words:["ROSA","TULIPAN","GIRASOL","MARGARITA"]},
  {name:"VEGETALES VERDES", words:["ESPINACA","BROCOLI","LECHUGA","APIO"]},
  {name:"MARIPOSAS", words:["MONARCA","ALAS","COLOR","MIGRACION"]},
  {name:"DINOSAURIOS FAMOSOS", words:["T-REX","TRICERATOPS","ESTEGOSAURIO","PTERODACTILO"]},

  // --- DAILY LIFE ---
  {name:"UTENSILIOS DE COCINA", words:["OLLA","SARTEN","CUCHILLO","ESPATULA"]},
  {name:"ELECTRODOMESTICOS", words:["NEVERA","LAVADORA","HORNO","MICROONDAS"]},
  {name:"HERRAMIENTAS MANUALES", words:["MARTILLO","DESTORNILLADOR","SIERRA","LLAVE"]},
  {name:"MATERIALES DE OFICINA", words:["GRAPADORA","PERFORADORA","CLIP","POST-IT"]},
  {name:"MUEBLES DEL HOGAR", words:["MESA","SILLA","ARMARIO","CAMA"]},
  {name:"PRENDAS DE VESTIR", words:["CAMISA","PANTALON","ZAPATOS","ABRIGO"]},
  {name:"ROPA DE INVIERNO", words:["CHAMARRA","BUFANDA","GUANTES","GORRO"]},
  {name:"COSAS DEL BANO", words:["TOALLA","CEPILLO","SHAMPOO","SECADOR"]},
  {name:"TAREAS DEL HOGAR", words:["BARRER","FREGAR","PLANCHAR","POLVO"]},
  {name:"PRODUCTOS LIMPIEZA", words:["JABON","DETERGENTE","CLORO","LIMPIADOR"]},
  {name:"COSAS DE OFICINA", words:["ESCRITORIO","SILLA","COMPUTADORA","ARCHIVERO"]},
  {name:"PARTES DE LA CASA", words:["COCINA","SALA","DORMITORIO","BANO"]},
  {name:"HERRAMIENTAS JARDIN", words:["PALA","RASTRILLO","TIJERA","MANGUERA"]},

  // --- MATH ---
  {name:"NUMEROS PRIMOS", words:["DOS","TRES","CINCO","SIETE"]},
  {name:"NUMEROS PARES", words:["DOS","CUATRO","SEIS","OCHO"]},
  {name:"NUMEROS IMPARES", words:["UNO","TRES","CINCO","SIETE"]},
  {name:"NUMEROS ROMANOS", words:["I","V","X","L"]},
  {name:"FIGURAS GEOMETRICAS", words:["CIRCULO","CUADRADO","TRIANGULO","RECTANGULO"]},
  {name:"OPERACIONES BASICAS", words:["SUMA","RESTA","MULTIPLICACION","DIVISION"]},
  {name:"UNIDADES TIEMPO", words:["SEGUNDO","MINUTO","HORA","DIA"]},
  {name:"UNIDADES LONGITUD", words:["METRO","CENTIMETRO","KILOMETRO","MILLA"]},
  {name:"FORMAS DE ONDA", words:["SENO","COSENO","CUADRADA","DIENTE"]},

  // --- ASTRONOMY ---
  {name:"PLANETAS SISTEMA SOLAR", words:["MARTE","VENUS","SATURNO","JUPITER"]},
  {name:"PLANETAS GASEOSOS", words:["JUPITER","SATURNO","URANO","NEPTUNO"]},
  {name:"ESTRELLAS FAMOSAS", words:["SIRIO","POLARIS","BETELGEUSE","VEGA"]},
  {name:"CONSTELACIONES", words:["ORION","OSA MAYOR","CASIOPEA","ESCORPION"]},
  {name:"CUERPOS CELESTES", words:["ESTRELLA","COMETA","ASTEROIDE","METEORITO"]},
  {name:"FASES DE LA LUNA", words:["NUEVA","CRECIENTE","LLENA","MENGUANTE"]},
  {name:"EVENTOS ASTRONOMICOS", words:["ECLIPSE","SOLSTICIO","EQUINOCCIO","LLUVIA"]},

  // --- TRANSPORTATION ---
  {name:"MEDIOS DE TRANSPORTE", words:["AUTO","TREN","AVION","BARCO"]},
  {name:"TRANSPORTE PUBLICO", words:["AUTOBUS","METRO","TAXI","TRANVIA"]},
  {name:"PARTES DE UN BARCO", words:["VELA","TIMON","ANCLA","PROA"]},
  {name:"PARTES DE AVION", words:["ALA","MOTOR","TREN","COLA"]},
  {name:"MARCAS DE AUTOS", words:["TOYOTA","FORD","HONDA","BMW"]},
  {name:"MARCAS DE LUJO", words:["TESLA","FERRARI","LAMBORGHINI","PORSCHE"]},

  // --- MISC ---
  {name:"MESES DEL ANO", words:["ENERO","MARZO","JUNIO","DICIEMBRE"]},
  {name:"DIAS DE LA SEMANA", words:["LUNES","MARTES","MIERCOLES","JUEVES"]},
  {name:"ESTACIONES DEL ANO", words:["PRIMAVERA","VERANO","OTONO","INVIERNO"]},
  {name:"SIGNOS DEL ZODIACO", words:["ARIES","TAURO","GEMINIS","CANCER"]},
  {name:"COLORES PRIMARIOS", words:["ROJO","AZUL","AMARILLO","VERDE"]},
  {name:"COLORES SECUNDARIOS", words:["NARANJA","VIOLETA","ROSADO","MARRON"]},
  {name:"COLORES CALIDOS", words:["ROJO","NARANJA","AMARILLO","ROSADO"]},
  {name:"COLORES FRIOS", words:["AZUL","VERDE","VIOLETA","TURQUESA"]},
  {name:"MARCAS DE ROPA", words:["ZARA","H&M","MANGO","UNIQLO"]},
  {name:"PERFUMES FAMOSOS", words:["CHANEL","DIOR","VERSACE","PACO"]},
  {name:"MARCAS DE RELOJES", words:["ROLEX","OMEGA","CASIO","SEIKO"]},
  {name:"EMISORAS DE RADIO", words:["LOS 40","KISS FM","RNE","CADENA SER"]},
  {name:"FESTIVIDADES", words:["NAVIDAD","PASCUA","HALLOWEEN","ANO NUEVO"]},
  {name:"PROFESIONES COMUNES", words:["MEDICO","BOMBERO","MAESTRO","POLICIA"]},
  {name:"PALABRAS DE ORIGEN GRIEGO", words:["DEMOCRACIA","FILOSOFIA","TEATRO","MATEMATICAS"]},
  {name:"PALABRAS LATINAS USUALES", words:["EXITOS","CURRICULUM","ALUMNI","ET CETERA"]},
  {name:"SIGLAS COMUNES", words:["ONG","OVNI","ADN","ONU"]},
  {name:"ACRONIMOS", words:["SIDA","LIDER","RADAR","SONAR"]},
  {name:"GENTILICIOS MEXICO", words:["YUCATECO","JALISCIENSE","REGIOMONTANO","CHILANGO"]},
  {name:"GENTILICIOS ESPANA", words:["MADRILENO","CATALAN","ANDALUZ","VALENCIANO"]},
  {name:"PALABRAS DE CINCO LETRAS", words:["ARBOL","CIUDAD","JAMON","PLATO"]},
  {name:"PALABRAS DE SEIS LETRAS", words:["VENTANA","JARDIN","CAMINO","PUERTA"]},
  {name:"PALABRAS DE SIETE LETRAS", words:["CAMISETA","ZAPATOS","ABRIGO","VENTANA"]},
  {name:"PALABRAS CON REPETICION", words:["COCO","PAPA","NENE","MAMA"]},
  {name:"PALABRAS INVARIABLES", words:["SALUD","CAOS","SED","HAMBRE"]},
  {name:"PALABRAS MASCULINAS", words:["PERRO","GATO","ARBOL","LIBRO"]},
  {name:"PALABRAS FEMENINAS", words:["CASA","MESA","FLOR","PUERTA"]},
  {name:"PALABRAS CON DIPTONGO", words:["TIERRA","BUENO","FUEGO","VIENTO"]},
  {name:"PALABRAS CON HIATO", words:["POESIA","TEATRO","LEER","CAER"]},
  {name:"PALABRAS TERMINAN EN 'A'", words:["CASA","MESA","SILLA","FLORA"]},
  {name:"PALABRAS TERMINAN EN 'O'", words:["PERRO","GATO","LIBRO","PLATO"]},

  // --- GEOGRAPHY EXTRA ---
  {name:"CAPITALES DE CENTROAMERICA", words:["MANAGUA","TEGUCIGALPA","GUATEMALA","PANAMA"]},
  {name:"CAPITALES DE EUROPA DEL ESTE", words:["PRAGA","VARSOVIA","BUDAPEST","KIEV"]},
  {name:"PAISES BAJOS", words:["HOLANDA","BELGICA","LUXEMBURGO","PAISES BAJOS"]},
  {name:"BANDERAS TRICOLORES", words:["MEXICO","ITALIA","FRANCIA","RUSIA"]},
  {name:"PAISES CON NOMBRE DE CIUDAD", words:["SINGAPUR","MONACO","VATICANO","LUXEMBURGO"]},
  {name:"CIUDADES CON RIO", words:["PARIS SENA","LONDRES TAMESIS","ROMA TIBER","VIENA DANUBIO"]},
  {name:"CIUDADES PORTUARIAS", words:["BARCELONA","VALENCIA","CADIZ","MALAGA"]},
  {name:"PAISES ANDINOS", words:["PERU","BOLIVIA","COLOMBIA","ECUADOR"]},
  {name:"PAISES CENTROAMERICA", words:["GUATEMALA","HONDURAS","EL SALVADOR","COSTA RICA"]},
  {name:"PAISES DEL GOLFO", words:["ARABIA","QATAR","EMIRATOS","KUWAIT"]},
  {name:"REGIONES DE ESPANA", words:["ANDALUCIA","CATALUNA","GALICIA","PAIS VASCO"]},
  {name:"PAISES CON MONARQUIA", words:["ESPANA","INGLATERRA","SUECIA","JAPON"]},
  {name:"PAISES DE ASIA SURESTE", words:["TAILANDIA","VIETNAM","INDONESIA","MALASIA"]},

  // --- SCIENCE EXTRA ---
  {name:"PARTICULAS SUBATOMICAS", words:["PROTON","NEUTRON","ELECTRON","FOTON"]},
  {name:"ELEMENTOS LIGEROS", words:["HIDROGENO","HELIO","LITIO","BERILIO"]},
  {name:"ELEMENTOS PESADOS", words:["URANIO","PLUTONIO","RADIO","POLONIO"]},
  {name:"ALEACIONES METALICAS", words:["ACERO","BRONCE","LATON","ARMCO"]},
  {name:"FENOMENOS QUIMICOS", words:["OXIDACION","REDUCCION","HIDROLISIS","COMBUSTION"]},
  {name:"TIPOS DE ROCAS", words:["IGNEAS","SEDIMENTARIAS","METAMORFICAS","CALIZA"]},
  {name:"PARTES DEL CEREBRO", words:["CEREBRO","CEREBELO","TALLO","HIPOTALAMO"]},
  {name:"NEUROTRANSMISORES", words:["SEROTONINA","DOPAMINA","ADRENALINA","MELATONINA"]},
  {name:"VITAMINAS ESENCIALES", words:["VITAMINA A","VITAMINA C","VITAMINA D","VITAMINA B12"]},
  {name:"ENFERMEDADES COMUNES", words:["GRIPE","RESFRIO","VARICELA","ALERGIA"]},
  {name:"ENFERMEDADES CRONICAS", words:["DIABETES","HIPERTENSION","ASMA","ARTRITIS"]},
  {name:"TRASTORNOS MENTALES", words:["ANSIEDAD","DEPRESION","TOC","ESQUIZOFRENIA"]},
  {name:"PROCESOS BIOLOGICOS", words:["MITOSIS","MEIOSIS","FOTOSINTESIS","RESPIRACION"]},
  {name:"BIOMAS TERRESTRES", words:["SELVA","DESIERTO","TUNDRA","SABANA"]},
  {name:"ECOSISTEMAS ACUATICOS", words:["MARINO","RIBERENO","PANTANO","ARRECIFE"]},
  {name:"CICLOS BIOGEOQUIMICOS", words:["CARBONO","NITROGENO","AGUA","FOSFORO"]},

  // --- SPORTS EXTRA ---
  {name:"EQUIPOS DE LA LIGA MX", words:["AMERICA","CHIVAS","CRUZ AZUL","RAYADOS"]},
  {name:"EQUIPOS DE LA PREMIER", words:["MANCHESTER CITY","ARSENAL","LIVERPOOL","CHELSEA"]},
  {name:"EQUIPOS DE LA LIGA", words:["REAL MADRID","BARCELONA","ATLETICO","SEVILLA"]},
  {name:"FUTBOLISTAS MEXICANOS", words:["CHICHARITO","RAFA MARQUEZ","GUARDADO","SANCHEZ"]},
  {name:"FUTBOLISTAS ARGENTINOS", words:["MESSI","MARADONA","DI MARIA","AGUERO"]},
  {name:"MUNDIALES SEDES", words:["MEXICO 70","ITALIA 90","FRANCIA 98","RUSIA 2018"]},
  {name:"CAMPEONES DEL MUNDO", words:["BRASIL","ALEMANIA","ARGENTINA","FRANCIA"]},
  {name:"ENTRENADORES FAMOSOS", words:["GUARDIOLA","KLOPP","ANCELOTTI","MOURINHO"]},
  {name:"DEPORTES DE RAQUETA", words:["TENIS","BADMINTON","SQUASH","PADEL"]},
  {name:"DEPORTES DE COMBATE", words:["BOXEO","MMA","ESGRIMA","LUCHA"]},
  {name:"ESTADIOS ICONICOS", words:["MARACANA","WEMBLEY","BERNABEU","CAMP NOU"]},
  {name:"COMENTARISTAS DEPORTIVOS", words:["RELATO","CRONICA","ANALISIS","ENTREVISTA"]},

  // --- LITERATURE ---
  {name:"NOVELAS FAMOSAS", words:["DON QUIJOTE","CIEN ANOS","LAZARILLO","CUMBRES"]},
  {name:"ESCRITORES ESPANOLES", words:["CERVANTES","LORCA","UNAMUNO","PEREZ GALDOS"]},
  {name:"ESCRITORES LATINOAMERICANOS", words:["GARCIA MARQUEZ","NERUDA","BORGES","PAZ"]},
  {name:"GENEROS LITERARIOS", words:["NOVELA","POESIA","DRAMA","ENSAYO"]},
  {name:"FIGURAS RETORICAS", words:["METAFORA","HIPERBOLE","IRONIA","SIMIL"]},
  {name:"POETAS FAMOSOS", words:["BECQUER","MACHADO","NERUDA","BENEDETTI"]},
  {name:"LIBROS DE AVENTURAS", words:["ISLA TESORO","ROBINSON CRUSOE","LA VUELTA","VEINTE MIL"]},
  {name:"PERSONAJES LITERARIOS", words:["SHERLOCK","HAMLET","QUIJOTE","HUCK FINN"]},

  // --- TECHNOLOGY EXTRA ---
  {name:"EMPRESAS DE INTERNET", words:["GOOGLE","AMAZON","META","NETFLIX"]},
  {name:"PLATAFORMAS DE VIDEO", words:["YOUTUBE","TIKTOK","INSTAGRAM","FACEBOOK"]},
  {name:"DISPOSITIVOS APPLE", words:["IPHONE","IPAD","MACBOOK","APPLE WATCH"]},
  {name:"SISTEMAS DE GPS", words:["WAZE","MAPS","TOMTOM","HERE"]},
  {name:"TIPOS DE INTELIGENCIA", words:["IA","MACHINE LEARNING","DEEP LEARNING","RED NEURONAL"]},
  {name:"REDES SOCIALES CHINAS", words:["TIKTOK","WECHAT","XIAOHONGSHU","DOUYIN"]},
  {name:"CONSOLAS DE VIDEOJUEGOS", words:["PLAYSTATION","XBOX","NINTENDO","PC"]},
  {name:"MARCAS DE CELULARES", words:["IPHONE","SAMSUNG","XIAOMI","HUAWEI"]},

  // --- FOOD EXTRA ---
  {name:"TIPOS DE PASTA", words:["SPAGHETTI","FETTUCCINE","PENNE","LASAGNA"]},
  {name:"INGREDIENTES MEXICANOS", words:["CHILE","FRIJOL","MAIZ","NOPAL"]},
  {name:"SALSAS PICANTES", words:["VALENTINA","CHOLULA","TABASCO","SRIBACHA"]},
  {name:"FRUTAS DE TEMPORADA", words:["SANDIA","MELON","UVA","NARANJA"]},
  {name:"VERDURAS DE RAIZ", words:["ZANAHORIA","PAPA","CEBOLLA","RABANO"]},
  {name:"TIPOS DE PIZZA", words:["MARGARITA","PEPPERONI","HAWAIANA","VEGETARIANA"]},
  {name:"BEBIDAS REFRESCANTES", words:["AGUA","SODA","JUGO","LIMONADA"]},
  {name:"DULCES TIPICOS", words:["CHURRO","TORRIJA","TURRON","MAZAPAN"]},
  {name:"POSTRES ESPANOLES", words:["CREMA CATALANA","TOCINO DE CIELO","ARROZ LECHE","BRAZO GITANO"]},
  {name:"HIERBAS PARA TE", words:["MANZANILLA","MENTA","HIERBABUENA","TE VERDE"]},
  {name:"MARISCOS COMUNES", words:["CAMARON","LANGOSTA","PULPO","MEJILLON"]},
  {name:"CORTES DE CERDO", words:["LOMO","COSTILLA","JAMON","PANCETA"]},
  {name:"TIPOS DE HONGOS", words:["CHAMPINON","SETAS","TRUFA","PORTOBELLO"]},

  // --- ANIMALS EXTRA ---
  {name:"ANIMALES DE AUSTRALIA", words:["CANGURO","KOALA","ORNITORRINCO","DINGO"]},
  {name:"ANIMALES DE LA SELVA", words:["TIGRE","MONO","GUACAMAYO","ANACONDA"]},
  {name:"ANIMALES DEL DESIERTO", words:["CAMELO","ESCORPION","RATON","SERPIENTE"]},
  {name:"ANIMALES ACORAZADOS", words:["TORTUGA","ARMADILLO","CANGREJO","CARACOL"]},
  {name:"ANIMALES DE COMPANIA", words:["PERRO","GATO","PEZ","HAMSTER"]},
  {name:"BALLENAS Y DELFINES", words:["AZUL","JOROBADA","ORCA","DELFIN"]},
  {name:"TIPOS DE TIBURONES", words:["BLANCO","MARTILLO","TORO","TIGRE"]},
  {name:"ANIMALES HERBIVOROS", words:["VACA","CABALLO","ELEFANTE","JIRAFA"]},
  {name:"ANIMALES CARNIVOROS", words:["LEON","LOBO","TIBURON","COCODRILO"]},
  {name:"ANIMALES OMNIVOROS", words:["OSO","CERDO","RATON","ZORRO"]},
  {name:"ANIMALES DE MITAD DE AGUA", words:["RANA","COCODRILO","HIPOPOTAMO","NUTRIA"]},
  {name:"ANIMALES QUE VUELAN", words:["AGUILA","MOSCA","MURCIELAGO","MARIPOSA"]},

  // --- MUSIC EXTRA ---
  {name:"CANTANTES LATINOS", words:["SHAKIRA","BAD BUNNY","ROSALIA","JLO"]},
  {name:"CANTANTES ROCK", words:["BOWIE","JAGGER","MERCURY","COBAIN"]},
  {name:"GRUPOS ESPANOLES", words:["ESTOPA","AMARAL","VETUSTA MORLA","LOQUILLO"]},
  {name:"BAILES LATINOS", words:["SALSA","TANGO","FLAMENCO","BACHATA"]},
  {name:"PLATAFORMAS DE MUSICA", words:["SPOTIFY","APPLE MUSIC","YOUTUBE MUSIC","TIDAL"]},
  {name:"BANDAS DE ROCK LATINO", words:["MANA","CAIFANES","SODA STEREO","HOMBRES G"]},
  {name:"INSTRUMENTOS DE TECLA", words:["PIANO","ORGANO","ACORDEON","SINTETIZADOR"]},
  {name:"FESTIVALES DE MUSICA", words:["COACHELLA","GLASTONBURY","LIVE AID","ROCK IN RIO"]},

  // --- ART EXTRA ---
  {name:"OBRAS DE ARTE FAMOSAS", words:["MONA LISA","ULTIMA CENA","NOCHE ESTRELLADA","GRITO"]},
  {name:"MUSEOS FAMOSOS", words:["LOUVRE","PRADO","METROPOLITANO","BRITANICO"]},
  {name:"PINTORES MEXICANOS", words:["FRIDA KAHLO","RIVERA","SIGUEIROS","TAMAYO"]},
  {name:"ESTILOS ARQUITECTURA", words:["GOTICO","ROMANICO","BARROCO","NEOCLASICO"]},
  {name:"FOTOGRAFIA", words:["CAMARA","LENTE","FLASH","TRIPODE"]},
  {name:"CINE DE TERROR", words:["PSICOSIS","EL RESPLANDOR","IT","EXORCISTA"]},
  {name:"CINE DE CIENCIA FICCION", words:["BLADE RUNNER","2001","MATRIX","STAR WARS"]},
  {name:"PERSONAJES DC", words:["BATMAN","SUPERMAN","WONDER WOMAN","FLASH"]},
  {name:"PELICULAS DE AVATAR", words:["TITANIC","AVATAR","STAR WARS","HARRY POTTER"]},
  {name:"SERIES DE TELEVISION", words: ["STRANGER THINGS","JUEGO TRONOS","BREAKING BAD","LOST"]},

  // --- MATHEMATICS EXTRA ---
  {name:"OPERACIONES ARITMETICAS", words:["SUMA","RESTA","MULTIPLICAR","DIVIDIR"]},
  {name:"CONCEPTOS GEOMETRICOS", words:["PUNTO","LINEA","PLANO","ANGULO"]},
  {name:"NUMEROS ENTEROS", words:["UNO","CERO","MENOS UNO","CIEN"]},
  {name:"NUMEROS FRACCIONARIOS", words:["MEDIO","TERCIO","CUARTO","QUINTO"]},
  {name:"FIGURAS EN 3D", words:["CUBO","ESFERA","CILINDRO","PIRAMIDE"]},
  {name:"FUNCIONES MATEMATICAS", words:["LINEAL","CUADRATICA","EXPONENCIAL","LOGARITMICA"]},
  {name:"MEDIDAS DE PESO", words:["GRAMO","KILO","TONELADA","LIBRA"]},
  {name:"MEDIDAS DE VOLUMEN", words:["LITRO","MILILITRO","GALON","BARRIL"]},

  // --- ASTRONOMY EXTRA ---
  {name:"ESTRELLAS CERCANAS", words:["SOL","ALFA CENTAURI","SIRIO","BARNARD"]},
  {name:"GALAXIAS FAMOSAS", words:["VIA LACTEA","ANDROMEDA","TRIANGULO","SOMBRERO"]},
  {name:"NEBULOSAS", words:["ORION","CANGREJO","ANILLO","AGUILA"]},
  {name:"AGUJEROS NEGROS", words:["SAGITARIO","CISNE","ANDROMEDA","M87"]},
  {name:"SATELITES NATURALES", words:["LUNA","EUROPA","TITAN","GANIMEDES"]},
  {name:"MISIONES ESPACIALES", words:["APOLO","VOYAGER","CASSINI","HUBBLE"]},

  // --- HISTORY EXTRA ---
  {name:"PERSONAJES HISTORICOS", words:["COLON","CORTES","PIZARRO","MAGELLANES"]},
  {name:"PRESIDENTES DE MEXICO", words:["OBRADOR","ENRIQUE PENA","CALDERON","VICENTE FOX"]},
  {name:"PRESIDENTES DE USA", words:["WASHINGTON","LINCOLN","ROOSEVELT","KENNEDY"]},
  {name:"REVOLUCIONARIOS", words:["MORELOS","HIDALGO","VILLA","ZAPATA"]},
  {name:"HECHOS HISTORICOS", words:["INDEPENDENCIA","REVOLUCION","CONQUISTA","COLONIA"]},
  {name:"TRATADOS FAMOSOS", words:["VERSALLES","YALTA","TORDESILLAS","GUADALUPE"]},
  {name:"CRUZADAS", words:["PRIMERA","SEGUNDA","TERCERA","INFANTIL"]},
  {name:"DINASTIAS REALES", words:["BORBON","HABSBURGO","TUDOR","ROMANOV"]},

  // --- EVERYDAY OBJECTS ---
  {name:"COSAS ELECTRICAS", words:["LAMPARA","VENTILADOR","TOSTADOR","PLANCHA"]},
  {name:"COSAS DE PLAYA", words:["ARENA","OLA","SOL","CONCHA"]},
  {name:"COSAS DE CAMPANA", words:["TIENDA","SACO","LINIERNA","BRUJULA"]},
  {name:"COSAS DE OFICINA", words:["ESCRITORIO","ARCHIVERO","SILLA","COMPUTADORA"]},
  {name:"COSAS DE COCINA", words:["OLLA","SARTEN","VASO","PLATO"]},
  {name:"COSAS DE BANO", words:["DUCHA","JABON","TOALLA","CEPILLO"]},
  {name:"COSAS DE PAPELERIA", words:["HOJA","SOBRE","CARPETA","ETIQUETA"]},
  {name:"COSAS QUE SE ROMPEN", words:["PLATO","VASO","JARRON","VENTANA"]},
  {name:"COSAS QUE SE EXPRIMEN", words:["NARANJA","LIMON","TORONJA","LIMA"]},
  {name:"COSAS QUE SE ABROCHAN", words:["CINTURON","BOTON","CREMALLERA","CORCHETE"]},
  {name:"COSAS QUE SE ENROLLAN", words:["CABLE","MANGA","CINTA","ALFOMBRA"]},
  {name:"COSAS QUE SE PLIEGAN", words:["ROPA","PAPEL","MANTEL","SERVILLETA"]},

  // --- SPANISH LANGUAGE ---
  {name:"PALABRAS CON 'G' SUAVE", words:["GATO","GOL","GUSTO","GOMA"]},
  {name:"PALABRAS CON 'G' FUERTE", words:["GENTE","GITANO","GELATINA","GESTION"]},
  {name:"PALABRAS CON 'C' SUAVE", words:["CENA","CINE","CIELO","CERO"]},
  {name:"PALABRAS CON 'C' FUERTE", words:["CASA","CAMA","CARRO","COLOR"]},
  {name:"EXPRESIONES COLOQUIALES", words:["QUE ONDA","NO MANCHES","A HUEVO","SIMON"]},
  {name:"REFLEXIONES", words:["NO","SIEMPRE","NUNCA","TAL VEZ"]},
  {name:"PALABRAS TERMINAN 'S'", words:["MARTES","LUNES","VIERNES","MIERCOLES"]},
  {name:"PALABRAS DE UNA SILABA", words:["DIOS","FLOR","CRUZ","VOZ"]},
  {name:"PALABRAS DE TRES LETRAS", words:["SOL","MAR","PAN","LUZ"]},
  {name:"PALABRAS DE CUATRO LETRAS", words:["CASA","MESA","GATO","PERRO"]},
  {name:"PALABRAS CON 2 VOCALES IGUALES", words:["AARON","COOPER","COORDENADA","AZAAR"]},

  // --- NATURE EXTRA ---
  {name:"FENOMENOS NATURALES", words:["TERREMOTO","TORNADO","HURACAN","TSUNAMI"]},
  {name:"FENOMENOS OPTICOS", words:["ARCOIRIS","ECLIPSE","AURORA","ESPEJISMO"]},
  {name:"FENOMENOS ATMOSFERICOS", words:["LLUVIA","NIEVE","GRANIZO","BRUMA"]},
  {name:"CLIMAS DEL MUNDO", words:["TROPICAL","MEDITERANEO","CONTINENTAL","POLAR"]},
  {name:"FORMACIONES ROCOSAS", words:["CABO","GOLFO","ESTRECHO","PENINSULA"]},
  {name:"RELIEVES TERRESTRES", words:["MONTE","VALLE","MESETA","LLANURA"]},
  {name:"CASCADAS FAMOSAS", words:["NIAGARA","IGUAZU","ANGEL","VICTORIA"]},
  {name:"BOSQUES DEL MUNDO", words:["AMAZONIA","TAIGA","SELVA","BOSQUE BOREAL"]},

  // --- HOBBIES ---
  {name:"PASATIEMPOS COMUNES", words:["LEER","JARDINERIA","COCINA","PINTURA"]},
  {name:"COLECCIONES COMUNES", words:["MONEDAS","ESTAMPILLAS","FIGURAS","TARJETAS"]},
  {name:"JUEGOS INFANTILES", words:["CARRERA","ESCONDITE","COMBA","PILLA"]},
  {name:"JUEGOS DE CARTAS", words:["POKER","BRIDGE","UNO","CORAZONES"]},
  {name:"JUEGOS DE MESA MODERNOS", words:["CATAN","PANDEMIC","MUNCHKIN","RISK"]},
  {name:"ROMPECABEZAS", words:["PUZZLE","CRUCIGRAMA","SOPA LETRAS","SUDOKU"]},
  {name:"ACTIVIDADES AL AIRE LIBRE", words:["CICLISMO","SENDERISMO","PICNIC","CAMPING"]},
  {name:"MANUALIDADES", words:["ORIGAMI","MACETA","PINTURA","TEJER"]},

  // --- ECONOMY ---
  {name:"TERMINOS ECONOMICOS", words:["INFLACION","CRECIMIENTO","RECESION","ESTANFLACION"]},
  {name:"MONEDAS DEL MUNDO", words:["DOLAR","EURO","PESO","LIBRA"]},
  {name:"BANCOS FAMOSOS", words:["SANTANDER","BBVA","CITIBANK","HSBC"]},
  {name:"INDICADORES ECONOMICOS", words:["PIB","IPC","TASA","INDICE"]},
  {name:"MODELOS DE NEGOCIO", words:["SaaS","E-COMMERCE","FRANQUICIA","MARKETPLACE"]},
  {name:"IMPUESTOS COMUNES", words:["IVA","ISR","IEPS","IMPUSTO"]},
  {name:"CRIPTOMONEDAS", words:["BITCOIN","ETHEREUM","CARDANO","SOLANA"]},
  {name:"TIPOS DE INVERSION", words:["ACCIONES","BONOS","FONDOS","BIENES RAICES"]},

  // --- BODY AND HEALTH ---
  {name:"PARTES DEL ROSTRO", words:["OJOS","NARIZ","BOCA","OREJAS"]},
  {name:"PARTES DE LA MANO", words:["DEDOS","PALMA","MUNECA","UNAS"]},
  {name:"HUESOS DEL BRAZO", words:["HUMERO","RADIO","CUBITO","FALANGES"]},
  {name:"PARTES DE LA PIERNA", words:["MUSLO","RODILLA","PANTORRILLA","TOBILLO"]},
  {name:"CUIDADO DE LA PIEL", words:["CREMA","PROTECTOR","HIDRATANTE","EXFOLIANTE"]},
  {name:"EJERCICIOS FISICOS", words:["SENTADILLAS","FLEXIONES","ABDOMINALES","CARRERA"]},
  {name:"HABITOS SALUDABLES", words:["DORMIR","COMER","EJERCICIO","HIDRATACION"]},

  // --- FASHION ---
  {name:"ACCESORIOS MODA", words:["BOLSO","CINTURON","BUFANDA","GORRO"]},
  {name:"JOYAS COMUNES", words:["ANILLO","COLLAR","PENDIENTES","PULSERA"]},
  {name:"CALZADO FEMENINO", words:["TACONES","BALLERINAS","SANDALIAS","BOTINES"]},
  {name:"TEJIDOS DE ROPA", words:["ALGODON","POLIESTER","LINO","LANA"]},
  {name:"ESTILOS DE MODA", words:["CASUAL","FORMAL","DEPORTIVO","ELEGANTE"]},
  {name:"DISENADORES FAMOSOS", words:["CHANEL","DIOR","ARMANI","VERSACE"]},

  // --- LINGUISTICS ADVANCED ---
  {name:"PALABRAS CON PREFIJO 'INTER-'", words:["INTERNACIONAL","INTERACTUAR","INTERMEDIO","INTERNET"]},
  {name:"PALABRAS CON PREFIJO 'TRANS-'", words:["TRANSPORTE","TRANSFORMAR","TRASNOCHAR","TRANSMISION"]},
  {name:"PALABRAS CON PREFIJO 'EX-'", words:["EXPRESIDENTE","EXMARIDO","EXCOMPANERO","EXALUMNO"]},
  {name:"PALABRAS CON SUFIJO '-ANTE'", words:["ESTUDIANTE","TRABAJANTE","CANTANTE","VIAJANTE"]},
  {name:"PALABRAS CON SUFIJO '-ABLE'", words:["AMABLE","COMIBLE","BEBIBLE","PROBABLE"]},
  {name:"PALABRAS CON SUFIJO '-AL'", words:["MUSICAL","NATURAL","CULTURAL","GENERAL"]},
  {name:"PALABRAS CON SUFIJO '-IVO'", words:["CREATIVO","POSITIVO","NEGATIVO","PROHIBIDO"]},
  {name:"PALABRAS AGUDAS TERMINAN VOCAL", words:["CAFE","SOFA","MAMA","PAPA"]},
  {name:"PALABRAS AGUDAS TERMINAN N/S", words:["AVION","BALON","ATUN","CAFETIN"]},
  {name:"PALABRAS GRAVES SIN ACENTO", words:["CASA","MESA","PERRO","GATO"]},
  {name:"PALABRAS GRAVES CON ACENTO", words:["ARBOL","CARACTER","CESAR","LAPIZ"]},
  {name:"PALABRAS ESDRUJULAS COMUNES", words:["TELEFONO","CAMARA","MUSICA","PAGINA"]},
  {name:"ANAGRAMAS COMUNES", words:["ROMA","AMOR","MORA","RAMO"]},
  {name:"PALABRAS CON DOS ACENTOS", words:["CAOTICO","VEHICULO","TRAIDO","REIR"]},
  {name:"PALABRAS QUE CAMBIAN CON S", words:["JABON","RINCON","VOLCAN","CAPITAN"]},

  // --- GEOGRAPHY CAPITALS ---
  {name:"CAPITALES NORDICAS", words:["ESTOCOLMO","OSLO","COPENHAGUE","HELSINKI"]},
  {name:"CAPITALES DEL CARIBE", words:["LA HABANA","SAN JUAN","SANTO DOMINGO","NASSAU"]},
  {name:"CIUDADES CON PUERTO", words:["BARCELONA","ROTTERDAM","HAMBURGO","SHANGAI"]},
  {name:"PAISES MEDITERRANEOS", words:["ESPANA","ITALIA","GRECIA","TURQUIA"]},
  {name:"PAISES ESCANDINAVOS", words:["SUECIA","NORUEGA","DINAMARCA","FINLANDIA"]},
  {name:"PAISES BALCANICOS", words:["CROACIA","SERBIA","BOSNIA","ALBANIA"]},

  // --- ASTRONOMY SOLAR SYSTEM ---
  {name:"ASTEROIDES FAMOSOS", words:["CERES","VESTA","PALLAS","JUNO"]},
  {name:"COMETAS FAMOSOS", words:["HALLEY","HALE BOP","ISON","BENNETT"]},
  {name:"PLANETAS INTERIORES", words:["MERCURIO","VENUS","TIERRA","MARTE"]},
  {name:"PLANETAS EXTERIORES", words:["JUPITER","SATURNO","URANO","NEPTUNO"]},
  {name:"TELESCOPIOS FAMOSOS", words:["HUBBLE","WEBB","KECK","GALILEO"]},

  // --- LANGUAGES ---
  {name:"IDIOMAS MAS HABLADOS", words:["INGLES","CHINO","ESPANOL","HINDI"]},
  {name:"IDIOMAS DE EUROPA", words:["ALEMAN","FRANCES","ITALIANO","PORTUGUES"]},
  {name:"IDIOMAS ASIATICOS", words:["MANDARIN","JAPONES","COREANO","TAILANDES"]},
  {name:"LENGUAS INDIGENAS", words:["NAHUATL","MAYA","QUECHUA","GUARANI"]},
  {name:"ALFABETOS DEL MUNDO", words:["LATINO","GRIEGO","CIRILICO","ARABE"]},
  {name:"SISTEMAS DE ESCRITURA", words:["JEROGLIFICO","CUNEIFORME","CHINO","KANA"]},

  // --- HOLIDAYS ---
  {name:"DIAS FESTIVOS MEXICO", words:["DIA MUERTOS","NAVIDAD","SEMANA SANTA","INDEPENDENCIA"]},
  {name:"DIAS FESTIVOS ESPANA", words:["NAVIDAD","SEMANA SANTA","CORPUS","HISPANIDAD"]},
  {name:"CELEBRACIONES MUNDIALES", words:["ANO NUEVO","NAVIDAD","HALLOWEEN","PASCUA"]},
  {name:"RITUALES Y TRADICIONES", words:["PONER PINO","CAMPANADAS","QUEMAR ANO","PIEDRA"]},
  {name:"COMIDAS DE NAVIDAD", words:["BACALAO","LECHON","TAMALES","ROMERITOS"]},

  // --- SCHOOL ---
  {name:"MATERIAS ESCOLARES", words:["MATEMATICAS","CIENCIAS","LENGUAJE","HISTORIA"]},
  {name:"UTILES ESCOLARES", words:["LAPIZ","CUADERNO","MOCHILA","REGLA"]},
  {name:"EXAMENES ESCOLARES", words:["PARCIAL","FINAL","EXTRAORDINARIO","GLOBAL"]},
  {name:"NIVELES EDUCATIVOS", words:["PREESCOLAR","PRIMARIA","SECUNDARIA","UNIVERSIDAD"]},
  {name:"CALIFICACIONES", words:["EXCELENTE","NOTABLE","BIEN","SUFICIENTE"]},
  {name:"ACRONIMOS ESCOLARES", words:["ESO","BACHILLER","FP","UNED"]},
  {name:"CARRERAS UNIVERSITARIAS", words:["MEDICINA","DERECHO","INGENIERIA","ARQUITECTURA"]},

  // --- FUNCTIONS & TOOLS ---
  {name:"VERBOS MODALES", words:["PODER","QUERER","DEBER","SOLER"]},
  {name:"VERBOS DE CAMBIO", words:["VOLVERSE","HACERSE","PONERSE","CONVERTIRSE"]},
  {name:"CONECTORES TEXTUALES", words:["ADEMAS","TAMBIEN","POR OTRO LADO","EN CONCLUSION"]},
  {name:"PALABRAS INTERROGATIVAS", words:["QUE","QUIEN","DONDE","CUANDO"]},
  {name:"PALABRAS DEMOSTRATIVAS", words:["ESTE","ESE","AQUELLO","ESO"]},
  {name:"POSESIVOS", words:["MI","TU","SU","NUESTRO"]},
  {name:"INDEFINIDOS", words:["ALGO","NADA","ALGUIEN","NADIE"]},

  // --- MIXED CATEGORIES ---
  {name:"COMBINACION DE COLORES", words:["BLANCO Y NEGRO","AZUL Y VERDE","ROJO Y AMARILLO","ROSA Y MORADO"]},
  {name:"EN LA MESA", words:["PLATO","VASO","TENEDOR","SERVILLETA"]},
  {name:"EN EL BANO", words:["DUCHA","INODORO","LAVAMANOS","ESPEJO"]},
  {name:"EN LA COCINA", words:["NEVERA","ESTUFA","LAVADORA","HORNO"]},
  {name:"EN EL DORMITORIO", words:["CAMA","ARMARIO","MESITA","LAMPARA"]},
  {name:"EN LA SALA", words:["SOFA","MESA DE CENTRO","TELEVISION","ESTANTE"]},
  {name:"EN EL JARDIN", words:["ARBOL","FLOR","CESPASTERIA","MACETA"]},
  {name:"EN EL CARRO", words:["VOLANTE","FRENO","ACELERADOR","ESPEJO"]},
  {name:"EN EL AVION", words:["TRIPULACION","PILOTO","AZAFATA","PASAJERO"]},

  // --- CULTURE ---
  {name:"PERSONAJES DE FICCIÓN", words:["SHERLOCK","POTTER","BOND","GATSBY"]},
  {name:"MITOS URBANOS", words:["CHUPACABRAS","LLA LORONA","EL CUCUY","PIEDRA"]},
  {name:"LEYENDAS MEXICANAS", words:["LLA LORONA","CHUPACABRAS","NAHUAL","MULATA"]},
  {name:"PERSONAJES DE ANIME", words:["GOKU","NARUTO","MONKEY","PUFF"]},
  {name:"PELICULAS DE TERROR", words:["PSICOSIS","RESPLANDOR","SABBATH","DRACULA"]},
  {name:"FILOSOFOS FAMOSOS", words:["SOCRATES","PLATON","ARISTOTELES","NIETZSCHE"]},
  {name:"PADRES DE LA CIENCIA", words:["NEWTON","EINSTEIN","DARWIN","GALILEO"]},

  // --- FOOD & DRINK ---
  {name:"BEBIDAS TRADICIONALES", words:["TEQUILA","PULQUE","HORCHATA","POZOLE"]},
  {name:"VINOS FAMOSOS", words:["TINTO","BLANCO","ROSADO","ESPUMOSO"]},
  {name:"COCTELES CLASICOS", words:["MARGARITA","MOJITO","PINA COLADA","DAIQUIRI"]},
  {name:"FRUTAS AMARILLAS", words:["MANGO","PIÑA","PLATANO","LIMON"]},
  {name:"FRUTAS ROJAS", words:["FRESA","FRAMBUESA","CEREZA","ARANDANO"]},
  {name:"VERDURAS CRUDAS", words:["LECHUGA","ZANAHORIA","APIO","PIMIENTO"]},
  {name:"TIPOS DE CARNE", words:["RES","POLLO","CERDO","CORDERO"]},
  {name:"DERIVADOS DE LECHE", words:["QUESO","YOGURT","CREMA","MANTEQUILLA"]},
  {name:"ESPECIES DE PESCADO", words:["SALMON","ATUN","MERLUZA","TRUCHA"]},
  {name:"PLATOS DE CUCHARA", words:["CALDO","SOPA","CREMA","POTAJE"]},

  // --- TRANSPORT ---
  {name:"MEDIOS DE TRANSPORTE ANTIGUOS", words:["CARRETA","DILIGENCIA","TRANVIA","VAPOR"]},
  {name:"PIEZAS DE BICICLETA", words:["MANUBRIO","LLANTA","CADENA","PEDAL"]},
  {name:"PARTES DE MOTOR", words:["MOTOR","BATERIA","RADIADOR","TRANSMISION"]},
  {name:"TIPOS DE BICICLETA", words:["MONTANA","RUTA","URBANA","ELECTRICA"]},
  {name:"MARCAS DE MOTOS", words:["HONDA","YAMAHA","KAWASAKI","DUCATI"]},
];

const COLORS = ["yellow", "green", "blue", "purple"];

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function generatePuzzles(count) {
  const usedNames = new Set();
  const puzzles = [];
  const pool = shuffle(ALL_CATEGORIES);

  let idx = 0;
  while (idx < pool.length && puzzles.length < count) {
    const yellow = pool[idx];
    if (usedNames.has(yellow.name)) { idx++; continue; }
    usedNames.add(yellow.name);

    const cats = [{name: yellow.name, words: yellow.words, color: "yellow"}];
    let needed = 3;

    for (let j = idx + 1; j < pool.length && needed > 0; j++) {
      const candidate = pool[j];
      if (!usedNames.has(candidate.name)) {
        usedNames.add(candidate.name);
        cats.push({name: candidate.name, words: candidate.words, color: COLORS[4 - needed]});
        needed--;
      }
    }

    if (needed === 0) {
      puzzles.push({
        id: "jason-" + (26 + puzzles.length),
        categories: cats
      });
    }
    idx++;
  }
  return puzzles;
}

const ALL_PUZZLES = generatePuzzles(125);
console.log(JSON.stringify(ALL_PUZZLES, null, 2));